packages:
  # include packages in subfolders (change as required)
  - 'apps/*'
  - 'packages/*'
  - 'apps/food-view/*'
  - 'apps/food-view/frontend/*'
  # if required, exclude directories
  - '!**/test/**'