// 'use client';

// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

// Todo: Write about this - mentioned in the README.md
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <div>
                        hoangesoftblog
                    </div>
                    <nav>
                        <ul>
                            <li><Link href="">Posts</Link></li>
                            <li><Link href="">Projects</Link></li>
                            <li><Link href="">About</Link></li>
                        </ul>
                    </nav>
                </header>
                {children}
            </body>
        </html>
    )
}
